ktor:
    application:
        modules:
            - com.ahyaemon.ApplicationKt.module
    deployment:
        port: 18080

jwt:
    secret: "secret"
    issuer: "http://0.0.0.0:18080"
    audience: "http://0.0.0.0:18080"
    realm: "com.ahyaemon.ktortraining"

db:
    url: "$DB_URL:jdbc:postgresql://localhost:15432/postgres"
    user: "$DB_USER:postgres"
    password: "$DB_PASSWORD:postgres"
